### ISSUE TITLE
Reduce number of tags further

### ISSUE THREAD

**Issue by max-sixty** [Aloso/to-html#17]
(Big fan of pomsky!)

I was hoping to use this crate to display colors for the errors in the [PRQL documentation](https://prql-lang.org/book/syntax.html).

One minor question — almost every character has its own `span` tag:

```
<span style='color:#a00'>Error:</span>
   <span style='color:#949494'>╭</span><span style='color:#949494'>─</span><span style='color:#949494'>[</span>:2:29<span style='color:#949494'>]</span>
   <span style='color:#949494'>│</span>
 <span style='color:#949494'>2 │</span> <span style='color:#b2b2b2'>d</span><span style='color:#b2b2b2'>e</span><span style='color:#b2b2b2'>r</span><span style='color:#b2b2b2'>i</span><span style='color:#b2b2b2'>v</span><span style='color:#b2b2b2'>e</span><span style='color:#b2b2b2'> </span><span style='color:#b2b2b2'>t</span><span style='color:#b2b2b2'>o</span><span style='color:#b2b2b2'>t</span><span style='color:#b2b2b2'>a</span><span style='color:#b2b2b2'>l</span><span style='color:#b2b2b2'>_</span><span style='color:#b2b2b2'>d</span><span style='color:#b2b2b2'>i</span><span style='color:#b2b2b2'>s</span><span style='color:#b2b2b2'>t</span><span style='color:#b2b2b2'>a</span><span style='color:#b2b2b2'>n</span><span style='color:#b2b2b2'>c</span><span style='color:#b2b2b2'>e</span><span style='color:#b2b2b2'> </span><span style='color:#b2b2b2'>=</span><span style='color:#b2b2b2'> </span><span style='color:#b2b2b2'>s</span><span style='color:#b2b2b2'>u</span><span style='color:#b2b2b2'>m</span><span style='color:#b2b2b2'> </span>distance
 <span style='color:#585858'>  │</span>                             ────┬───
 <span style='color:#585858'>  │</span>                                 ╰───── Unknown name distance
<span style='color:#949494'>───╯</span>
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/5635139/226230272-f68308eb-705d-45e3-8155-9c5c541a5ac6.png">

I have very little experience with ANSI color codes, so possibly this is caused by something upstream. Ariadne is the library that produces the errors.

Thanks!

**Comment by CosmicHorrorDev** [comment]
It should be possible to do a pass over things where you discard styling that's already applied. Chances are the original library is applying the ansi code for each character which would certainly be good for upstream to fix too

I can make the changes for this project though 👍

**Comment by Aloso** [comment]
to-html adds a span for each ANSI code in the output. If there's span for each character, that probably means that the command you ran produces unnecessarily many ANSI codes. But it makes sense for to-html to detect subsequent spans with the same styles to simplify the output.

**Comment by max-sixty** [comment]
Thanks @Aloso & @CosmicHorrorDev !
