### ISSUE TITLE
Provide shell completions

### ISSUE THREAD

**Issue by CosmicHorrorDev** [Aloso/to-html#21]
I'm planning on adding support for generating shell completions (through [`clap_complete`](https://crates.io/crates/clap_complete)). There are a few different ways that it can be handled, so it figured it would be good to open an issue to discuss things first. The three ways I know of are

1. Generate completions at runtime using something like a `--gen-completion {SHELL}` flag
2. Generate completions at build time using a `build.rs`
3. Generate completions ahead of time using a [`cargo-xtask`](https://github.com/matklad/cargo-xtask) task that is run manually before a release

There is no clear winner unfortunately:

- 1 gives users an obvious way to create the completion by just having the binary at the expense of being a bit clunky (3 is close, but cargo doesn't provide an obvious way for users to install these completions if they install it through cargo)
- 2 only has to be a build dep and 3 doesn't add any dependencies to the binary at all
- 1 and 2 are both kept up to date automatically without having to manually run anything

Any thoughts?

**Comment by Aloso** [comment]
I don't have a strong opinion on this. I'd just generate the completions at build time and publish them in the next GitHub release. I'd also add them to the AUR package so they're installed automatically.

Generating them at runtime is a "nice to have", but not necessary; users can download and install the completions with curl.

**Comment by CosmicHorrorDev** [comment]
Sounds like a build script is the winner then! I'll work on opening a PR for that tomorrow

> I'd also add them to the AUR package so they're installed automatically.

Will do :)
