### ISSUE TITLE
lazy-init should be a default feature

### ISSUE THREAD

**Issue by jclulow** [Aloso/to-html#32]
The README suggests:

> When the **lazy-init** feature is enabled, regexes are lazily initialized, which is more efficient if you want to convert A LOT of strings. The performance difference has not been tested.

I recently ran into a large performance-related regression as a result of our use of this crate.  The **lazy-init** feature should be a default feature to avoid people having to discover this on their own!

![slow](https://github.com/user-attachments/assets/20e5aec6-f2b8-413f-ac3a-40235d8018c1)

You can see in the flamegraph above that most of the on-CPU time in the server is spent recompiling the regular expression.

**Comment by Aloso** [comment]
Yes, let's enable it by default. Also, I believe it still uses the `lazy_static` crate, which is no longer needed since `OnceLock` is in the standard library.
